name: ci

on:
  push:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # ui
      - working-directory: ui
        run: pnpm install
      - working-directory: ui
        run: pnpm test
      - working-directory: ui
        run: pnpm build
      
      # go
      - run: go test ./...
      - run: go install
